# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Dog.create(name: 'Louie', size: "medium", age: 5, left_alone: "yes", housetrained: "yes", needs_another_dog: "no", kids: "yes", activity: "low", yard: "no", url: "http://cdn-www.dailypuppy.com/dog-images/gabby-the-miniature-poodle_66848_2012-07-14_w450.jpg", user_id: 2, blurb: "Louie is our calmest dog. He just likes to sit in your lap. He's great with kids and really friendly with other dogs.")
Dog.create(name: 'Rusty', size: "small", age: 3, left_alone: "yes", housetrained: "yes", needs_another_dog: "yes", kids: "no", activity: "low", yard: "no", url: "https://s3.amazonaws.com/pet-uploads.adoptapet.com/8/8/4/60064192.jpg?336w", user_id: 2, blurb: "Rusty came in with his sister, Princess. He's very calm and sweet and only about a year old.")
Dog.create(name: 'Oliver', size: "medium", age: 10, left_alone: "yes", housetrained: "yes", needs_another_dog: "no", kids: "no", activity: "medium", yard: "no", url: "http://www.allmutt.com/wp-content/uploads/2014/04/mutt-chihuahua-rat-terrier-mix-300x225.jpg", user_id: 2, blurb: "Oliver is one of our sweetest dogs! He's about 10 years old and completely housetrained. He's very calm and friendly and would be ok being left home all day while you're at work.")
Dog.create(name: 'Ricky', size: "small", age: 4, left_alone: "no", housetrained: "yes", needs_another_dog: "no", kids: "no", activity: "medium", yard: "no", url: "http://files.dogster.com/pix/dogs/50/82250/82250_1171292498.jpg", user_id: 2, blurb: "Ricky lived with a home for a long time so is completely house trained and good with other dogs. He is sometimes nippy with sudden movements so isn't recommended for families with small children. Is and otherwise very fun and playful dog.")
Dog.create(name: 'Dolce', size: "medium", age: 2, left_alone: "no", housetrained: "no", needs_another_dog: "yes", kids: "no", activity: "high", yard: "yes", url: "http://www.maltesemaniac.com/images/maltese-cross-shih-tzu-moppy-21340715.jpg", user_id: 2, blurb: "Dolce is by far our most lively and playful dog. He would love a yard and a fence tall enough he can't jump over. He loves to play with his sister, Gabana and can hopefully find a home with her.")
Dog.create(name: 'Gabana', size: "medium", age: 2, left_alone: "yes", housetrained: "yes", needs_another_dog: "yes", kids: "no", activity: "low", yard: "yes", url: "http://www.smalldogplace.com/images/Jessie-Australian-Terrier-ShihTzu.jpg", user_id: 2, blurb: "Gabana is the slightly calmer sister of Dolce. She still loves to play and can hopefully find a home with her brother, Dolce.")
Dog.create(name: 'Gabana', size: "small", age: 4, left_alone: "no", housetrained: "no", needs_another_dog: "no", kids: "no", activity: "high", yard: "yes", url: "http://vignette1.wikia.nocookie.net/dogs-cats/images/0/0b/White_Shih_Tzu.jpg/revision/latest?cb=20091219103356", user_id: 2, blurb: "Happy was a stray for a long time. He's a very fun and lively dog but isn't the most adjusted to home-life. Hopefully he can go to a home that can invest a little more time into training him.")
Dog.create(name: 'Princess', size: "small", age: 2, left_alone: "yes", housetrained: "yes", needs_another_dog: "yes", kids: "no", activity: "low", yard: "no", url: "https://s3.amazonaws.com/pet-uploads.adoptapet.com/b/7/0/108069950.jpg?336w", user_id: 2, blurb: "Princess is the sister of Rusty. She's very calm and sweet. She's had spinal surgery a few months ago and has just a little trouble walking.")
Dog.create(name: 'Giovanni', size: "medium", age: 2, left_alone: "no", housetrained: "yes", needs_another_dog: "yes", kids: "no", activity: "medium", yard: "no", url: "https://s3.amazonaws.com/pet-uploads.adoptapet.com/9/c/1/102540088.jpg?336w", user_id: 2, blurb: "Giovanni is a 2 year old pure bred shih tzu. He sometimes gets a little nervous so needs another dog around. Perfect for a family that already has a friendly dog or he would love to find a home with his best friend, Ricky who is also at this shelter.")

User.create(email: "chloe@gmail.com", password: "password", shelter_name: "Death Row Dogs Shelter", address: "57611, Sherman Oaks, CA 91413", phone: "(818) 232-0775")
